### ISSUE TITLE
How come this is not implemented cod4x

### ISSUE THREAD

**Issue by MichaelHillcox** [callofduty4x/cod4x_plugin_http#1]
title says its all.

**Comment by D4edalus** [comment]
plugins extend the base functionality of the server. this functionality is by far not _needed_ to run a cod4x server. the best thing about plugins is probably that it enables every to easily extend the server. as this isnt trivial having plugins showing some source how to do it is beneficial for others hopefully.

**Comment by MichaelHillcox** [comment]
That's fine. Thanks for answering my questions :)
